const capitals = [
  { code: "AF", name: "Kabul" },
  { code: "AL", name: "Tirana" },
  { code: "DZ", name: "Algiers" },
  { code: "AD", name: "Andorra la Vella" },
  { code: "AO", name: "Luanda" },
  { code: "AG", name: "St. John's" },
  { code: "AR", name: "Buenos Aires" },
  { code: "AM", name: "Yerevan" },
  { code: "AU", name: "Canberra" },
  { code: "AT", name: "Vienna" },
  { code: "AZ", name: "Baku" },
  { code: "BS", name: "Nassau" },
  { code: "BH", name: "Manama" },
  { code: "BD", name: "Dhaka" },
  { code: "BB", name: "Bridgetown" },
  { code: "BY", name: "Minsk" },
  { code: "BE", name: "Brussels" },
  { code: "BZ", name: "Belmopan" },
  { code: "BJ", name: "Porto-Novo" },
  { code: "BT", name: "Thimphu" },
  { code: "BO", name: "Sucre" },
  { code: "BA", name: "Sarajevo" },
  { code: "BW", name: "Gaborone" },
  { code: "BR", name: "Brasília" },
  { code: "BN", name: "Bandar Seri Begawan" },
  { code: "BG", name: "Sofia" },
  { code: "BF", name: "Ouagadougou" },
  { code: "BI", name: "Gitega" },
  { code: "CV", name: "Praia" },
  { code: "KH", name: "Phnom Penh" },
  { code: "CM", name: "Yaoundé" },
  { code: "CA", name: "Ottawa" },
  { code: "CF", name: "Bangui" },
  { code: "TD", name: "N'Djamena" },
  { code: "CL", name: "Santiago" },
  { code: "CN", name: "Beijing" },
  { code: "CO", name: "Bogotá" },
  { code: "KM", name: "Moroni" },
  { code: "CG", name: "Brazzaville" },
  { code: "CD", name: "Kinshasa" },
  { code: "CR", name: "San José" },
  { code: "CI", name: "Yamoussoukro" },
  { code: "HR", name: "Zagreb" },
  { code: "CU", name: "Havana" },
  { code: "CY", name: "Nicosia" },
  { code: "CZ", name: "Prague" },
  { code: "DK", name: "Copenhagen" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Roseau" },
  { code: "DO", name: "Santo Domingo" },
  { code: "EC", name: "Quito" },
  { code: "EG", name: "Cairo" },
  { code: "SV", name: "San Salvador" },
  { code: "GQ", name: "Malabo" },
  { code: "ER", name: "Asmara" },
  { code: "EE", name: "Tallinn" },
  { code: "SZ", name: "Mbabane" },
  { code: "ET", name: "Addis Ababa" },
  { code: "FJ", name: "Suva" },
  { code: "FI", name: "Helsinki" },
  { code: "FR", name: "Paris" },
  { code: "GA", name: "Libreville" },
  { code: "GM", name: "Banjul" },
  { code: "GE", name: "Tbilisi" },
  { code: "DE", name: "Berlin" },
  { code: "GH", name: "Accra" },
  { code: "GR", name: "Athens" },
  { code: "GD", name: "St. George's" },
  { code: "GT", name: "Guatemala City" },
  { code: "GN", name: "Conakry" },
  { code: "GW", name: "Bissau" },
  { code: "GY", name: "Georgetown" },
  { code: "HT", name: "Port-au-Prince" },
  { code: "HN", name: "Tegucigalpa" },
  { code: "HU", name: "Budapest" },
  { code: "IS", name: "Reykjavík" },
  { code: "IN", name: "New Delhi" },
  { code: "ID", name: "Jakarta" },
  { code: "IR", name: "Tehran" },
  { code: "IQ", name: "Baghdad" },
  { code: "IE", name: "Dublin" },
  { code: "IL", name: "Jerusalem" },
  { code: "IT", name: "Rome" },
  { code: "JM", name: "Kingston" },
  { code: "JP", name: "Tokyo" },
  { code: "JO", name: "Amman" },
  { code: "KZ", name: "Astana" },
  { code: "KE", name: "Nairobi" },
  { code: "KI", name: "Tarawa" },
  { code: "XK", name: "Pristina" },
  { code: "KW", name: "Kuwait City" },
  { code: "KG", name: "Bishkek" },
  { code: "LA", name: "Vientiane" },
  { code: "LV", name: "Riga" },
  { code: "LB", name: "Beirut" },
  { code: "LS", name: "Maseru" },
  { code: "LR", name: "Monrovia" },
  { code: "LY", name: "Tripoli" },
  { code: "LI", name: "Vaduz" },
  { code: "LT", name: "Vilnius" },
  { code: "LU", name: "Luxembourg" },
  { code: "MG", name: "Antananarivo" },
  { code: "MW", name: "Lilongwe" },
  { code: "MY", name: "Kuala Lumpur" },
  { code: "MV", name: "Malé" },
  { code: "ML", name: "Bamako" },
  { code: "MT", name: "Valletta" },
  { code: "MH", name: "Majuro" },
  { code: "MR", name: "Nouakchott" },
  { code: "MU", name: "Port Louis" },
  { code: "MX", name: "Mexico City" },
  { code: "FM", name: "Palikir" },
  { code: "MD", name: "Chișinău" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Ulaanbaatar" },
  { code: "ME", name: "Podgorica" },
  { code: "MA", name: "Rabat" },
  { code: "MZ", name: "Maputo" },
  { code: "MM", name: "Naypyidaw" },
  { code: "NA", name: "Windhoek" },
  { code: "NR", name: "Yaren" },
  { code: "NP", name: "Kathmandu" },
  { code: "NL", name: "Amsterdam" },
  { code: "NZ", name: "Wellington" },
  { code: "NI", name: "Managua" },
  { code: "NE", name: "Niamey" },
  { code: "NG", name: "Abuja" },
  { code: "KP", name: "Pyongyang" },
  { code: "MK", name: "Skopje" },
  { code: "NO", name: "Oslo" },
  { code: "OM", name: "Muscat" },
  { code: "PK", name: "Islamabad" },
  { code: "PW", name: "Ngerulmud" },
  { code: "PS", name: "Ramallah" },
  { code: "PA", name: "Panama City" },
  { code: "PG", name: "Port Moresby" },
  { code: "PY", name: "Asunción" },
  { code: "PE", name: "Lima" },
  { code: "PH", name: "Manila" },
  { code: "PL", name: "Warsaw" },
  { code: "PT", name: "Lisbon" },
  { code: "QA", name: "Doha" },
  { code: "RO", name: "Bucharest" },
  { code: "RU", name: "Moscow" },
  { code: "RW", name: "Kigali" },
  { code: "KN", name: "Basseterre" },
  { code: "LC", name: "Castries" },
  { code: "VC", name: "Kingstown" },
  { code: "WS", name: "Apia" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé" },
  { code: "SA", name: "Riyadh" },
  { code: "SN", name: "Dakar" },
  { code: "RS", name: "Belgrade" },
  { code: "SC", name: "Victoria" },
  { code: "SL", name: "Freetown" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Bratislava" },
  { code: "SI", name: "Ljubljana" },
  { code: "SB", name: "Honiara" },
  { code: "SO", name: "Mogadishu" },
  { code: "ZA", name: "Pretoria" },
  { code: "KR", name: "Seoul" },
  { code: "SS", name: "Juba" },
  { code: "ES", name: "Madrid" },
  { code: "LK", name: "Sri Jayawardenepura Kotte" },
  { code: "SD", name: "Khartoum" },
  { code: "SR", name: "Paramaribo" },
  { code: "SE", name: "Stockholm" },
  { code: "CH", name: "Bern" },
  { code: "SY", name: "Damascus" },
  { code: "TW", name: "Taipei" },
  { code: "TJ", name: "Dushanbe" },
  { code: "TZ", name: "Dodoma" },
  { code: "TH", name: "Bangkok" },
  { code: "TL", name: "Dili" },
  { code: "TG", name: "Lomé" },
  { code: "TO", name: "Nuku'alofa" },
  { code: "TT", name: "Port of Spain" },
  { code: "TN", name: "Tunis" },
  { code: "TR", name: "Ankara" },
  { code: "TM", name: "Ashgabat" },
  { code: "TV", name: "Funafuti" },
  { code: "UG", name: "Kampala" },
  { code: "UA", name: "Kyiv" },
  { code: "AE", name: "Abu Dhabi" },
  { code: "GB", name: "London" },
  { code: "US", name: "Washington, D.C." },
  { code: "UY", name: "Montevideo" },
  { code: "UZ", name: "Tashkent" },
  { code: "VU", name: "Port Vila" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Caracas" },
  { code: "VN", name: "Hanoi" },
  { code: "YE", name: "Sana'a" },
  { code: "ZM", name: "Lusaka" },
  { code: "ZW", name: "Harare" },
];

export const getRandomCapital = () => {
  return capitals[Math.floor(Math.random() * capitals.length)];
};
