const capitals = [
  { code: "AF", capital: "Kabul", image: "/images/capitals/1.jpg" },
  { code: "AL", capital: "Tirana", image: "/images/capitals/2.jpg" },
  { code: "DZ", capital: "Algiers", image: "/images/capitals/3.jpg" },
  { code: "AD", capital: "Andorra la Vella", image: "/images/capitals/4.jpg" },
  { code: "AO", capital: "Luanda", image: "/images/capitals/5.jpg" },
  { code: "AG", capital: "St. John's", image: "/images/capitals/6.jpg" },
  { code: "AR", capital: "Buenos Aires", image: "/images/capitals/7.jpg" },
  { code: "AM", capital: "Yerevan", image: "/images/capitals/1.jpg" },
  { code: "AU", capital: "Canberra", image: "/images/capitals/1.jpg" },
  { code: "AT", capital: "Vienna", image: "/images/capitals/1.jpg" },
  { code: "AZ", capital: "Baku", image: "/images/capitals/1.jpg" },
  { code: "BS", capital: "Nassau", image: "/images/capitals/1.jpg" },
  { code: "BH", capital: "Manama", image: "/images/capitals/1.jpg" },
  { code: "BD", capital: "Dhaka", image: "/images/capitals/1.jpg" },
  { code: "BB", capital: "Bridgetown", image: "/images/capitals/1.jpg" },
  { code: "BY", capital: "Minsk", image: "/images/capitals/1.jpg" },
  { code: "BE", capital: "Brussels", image: "/images/capitals/1.jpg" },
  { code: "BZ", capital: "Belmopan", image: "/images/capitals/1.jpg" },
  { code: "BJ", capital: "Porto-Novo", image: "/images/capitals/1.jpg" },
  { code: "BT", capital: "Thimphu", image: "/images/capitals/1.jpg" },
  { code: "BO", capital: "Sucre", image: "/images/capitals/1.jpg" },
  { code: "BA", capital: "Sarajevo", image: "/images/capitals/1.jpg" },
  { code: "BW", capital: "Gaborone", image: "/images/capitals/1.jpg" },
  { code: "BR", capital: "Brasília", image: "/images/capitals/1.jpg" },
  {
    code: "BN",
    capital: "Bandar Seri Begawan",
    image: "/images/capitals/1.jpg",
  },
  { code: "BG", capital: "Sofia", image: "/images/capitals/1.jpg" },
  { code: "BF", capital: "Ouagadougou", image: "/images/capitals/1.jpg" },
  { code: "BI", capital: "Gitega", image: "/images/capitals/1.jpg" },
  { code: "CV", capital: "Praia", image: "/images/capitals/1.jpg" },
  { code: "KH", capital: "Phnom Penh", image: "/images/capitals/1.jpg" },
  { code: "CM", capital: "Yaoundé", image: "/images/capitals/1.jpg" },
  { code: "CA", capital: "Ottawa", image: "/images/capitals/1.jpg" },
  { code: "CF", capital: "Bangui", image: "/images/capitals/1.jpg" },
  { code: "TD", capital: "N'Djamena", image: "/images/capitals/1.jpg" },
  { code: "CL", capital: "Santiago", image: "/images/capitals/1.jpg" },
  { code: "CN", capital: "Beijing", image: "/images/capitals/1.jpg" },
  { code: "CO", capital: "Bogotá", image: "/images/capitals/1.jpg" },
  { code: "KM", capital: "Moroni", image: "/images/capitals/1.jpg" },
  { code: "CG", capital: "Brazzaville", image: "/images/capitals/1.jpg" },
  { code: "CD", capital: "Kinshasa", image: "/images/capitals/1.jpg" },
  { code: "CR", capital: "San José", image: "/images/capitals/1.jpg" },
  { code: "CI", capital: "Yamoussoukro", image: "/images/capitals/1.jpg" },
  { code: "HR", capital: "Zagreb", image: "/images/capitals/1.jpg" },
  { code: "CU", capital: "Havana", image: "/images/capitals/1.jpg" },
  { code: "CY", capital: "Nicosia", image: "/images/capitals/1.jpg" },
  { code: "CZ", capital: "Prague", image: "/images/capitals/1.jpg" },
  { code: "DK", capital: "Copenhagen", image: "/images/capitals/1.jpg" },
  { code: "DJ", capital: "Djibouti", image: "/images/capitals/1.jpg" },
  { code: "DM", capital: "Roseau", image: "/images/capitals/1.jpg" },
  { code: "DO", capital: "Santo Domingo", image: "/images/capitals/1.jpg" },
  { code: "EC", capital: "Quito", image: "/images/capitals/1.jpg" },
  { code: "EG", capital: "Cairo", image: "/images/capitals/1.jpg" },
  { code: "SV", capital: "San Salvador", image: "/images/capitals/1.jpg" },
  { code: "GQ", capital: "Malabo", image: "/images/capitals/1.jpg" },
  { code: "ER", capital: "Asmara", image: "/images/capitals/1.jpg" },
  { code: "EE", capital: "Tallinn", image: "/images/capitals/1.jpg" },
  { code: "SZ", capital: "Mbabane", image: "/images/capitals/1.jpg" },
  { code: "ET", capital: "Addis Ababa", image: "/images/capitals/1.jpg" },
  { code: "FJ", capital: "Suva", image: "/images/capitals/1.jpg" },
  { code: "FI", capital: "Helsinki", image: "/images/capitals/1.jpg" },
  { code: "FR", capital: "Paris", image: "/images/capitals/1.jpg" },
  { code: "GA", capital: "Libreville", image: "/images/capitals/1.jpg" },
  { code: "GM", capital: "Banjul", image: "/images/capitals/1.jpg" },
  { code: "GE", capital: "Tbilisi", image: "/images/capitals/1.jpg" },
  { code: "DE", capital: "Berlin", image: "/images/capitals/1.jpg" },
  { code: "GH", capital: "Accra", image: "/images/capitals/1.jpg" },
  { code: "GR", capital: "Athens", image: "/images/capitals/1.jpg" },
  { code: "GD", capital: "St. George's", image: "/images/capitals/1.jpg" },
  { code: "GT", capital: "Guatemala City", image: "/images/capitals/1.jpg" },
  { code: "GN", capital: "Conakry", image: "/images/capitals/1.jpg" },
  { code: "GW", capital: "Bissau", image: "/images/capitals/1.jpg" },
  { code: "GY", capital: "Georgetown", image: "/images/capitals/1.jpg" },
  { code: "HT", capital: "Port-au-Prince", image: "/images/capitals/1.jpg" },
  { code: "HN", capital: "Tegucigalpa", image: "/images/capitals/1.jpg" },
  { code: "HU", capital: "Budapest", image: "/images/capitals/1.jpg" },
  { code: "IS", capital: "Reykjavík", image: "/images/capitals/1.jpg" },
  { code: "IN", capital: "New Delhi", image: "/images/capitals/1.jpg" },
  { code: "ID", capital: "Jakarta", image: "/images/capitals/1.jpg" },
  { code: "IR", capital: "Tehran", image: "/images/capitals/1.jpg" },
  { code: "IQ", capital: "Baghdad", image: "/images/capitals/1.jpg" },
  { code: "IE", capital: "Dublin", image: "/images/capitals/1.jpg" },
  { code: "IL", capital: "Jerusalem", image: "/images/capitals/1.jpg" },
  { code: "IT", capital: "Rome", image: "/images/capitals/1.jpg" },
  { code: "JM", capital: "Kingston", image: "/images/capitals/1.jpg" },
  { code: "JP", capital: "Tokyo", image: "/images/capitals/1.jpg" },
  { code: "JO", capital: "Amman", image: "/images/capitals/1.jpg" },
  { code: "KZ", capital: "Astana", image: "/images/capitals/1.jpg" },
  { code: "KE", capital: "Nairobi", image: "/images/capitals/1.jpg" },
  { code: "KI", capital: "Tarawa", image: "/images/capitals/1.jpg" },
  { code: "XK", capital: "Pristina", image: "/images/capitals/1.jpg" },
  { code: "KW", capital: "Kuwait City", image: "/images/capitals/1.jpg" },
  { code: "KG", capital: "Bishkek", image: "/images/capitals/1.jpg" },
  { code: "LA", capital: "Vientiane", image: "/images/capitals/1.jpg" },
  { code: "LV", capital: "Riga", image: "/images/capitals/1.jpg" },
  { code: "LB", capital: "Beirut", image: "/images/capitals/1.jpg" },
  { code: "LS", capital: "Maseru", image: "/images/capitals/1.jpg" },
  { code: "LR", capital: "Monrovia", image: "/images/capitals/1.jpg" },
  { code: "LY", capital: "Tripoli", image: "/images/capitals/1.jpg" },
  { code: "LI", capital: "Vaduz", image: "/images/capitals/1.jpg" },
  { code: "LT", capital: "Vilnius", image: "/images/capitals/1.jpg" },
  { code: "LU", capital: "Luxembourg", image: "/images/capitals/1.jpg" },
  { code: "MG", capital: "Antananarivo", image: "/images/capitals/1.jpg" },
  { code: "MW", capital: "Lilongwe", image: "/images/capitals/1.jpg" },
  { code: "MY", capital: "Kuala Lumpur", image: "/images/capitals/1.jpg" },
  { code: "MV", capital: "Malé", image: "/images/capitals/1.jpg" },
  { code: "ML", capital: "Bamako", image: "/images/capitals/1.jpg" },
  { code: "MT", capital: "Valletta", image: "/images/capitals/1.jpg" },
  { code: "MH", capital: "Majuro", image: "/images/capitals/1.jpg" },
  { code: "MR", capital: "Nouakchott", image: "/images/capitals/1.jpg" },
  { code: "MU", capital: "Port Louis", image: "/images/capitals/1.jpg" },
  { code: "MX", capital: "Mexico City", image: "/images/capitals/1.jpg" },
  { code: "FM", capital: "Palikir", image: "/images/capitals/1.jpg" },
  { code: "MD", capital: "Chișinău", image: "/images/capitals/1.jpg" },
  { code: "MC", capital: "Monaco", image: "/images/capitals/1.jpg" },
  { code: "MN", capital: "Ulaanbaatar", image: "/images/capitals/1.jpg" },
  { code: "ME", capital: "Podgorica", image: "/images/capitals/1.jpg" },
  { code: "MA", capital: "Rabat", image: "/images/capitals/1.jpg" },
  { code: "MZ", capital: "Maputo", image: "/images/capitals/1.jpg" },
  { code: "MM", capital: "Naypyidaw", image: "/images/capitals/1.jpg" },
  { code: "NA", capital: "Windhoek", image: "/images/capitals/1.jpg" },
  { code: "NR", capital: "Yaren", image: "/images/capitals/1.jpg" },
  { code: "NP", capital: "Kathmandu", image: "/images/capitals/1.jpg" },
  { code: "NL", capital: "Amsterdam", image: "/images/capitals/1.jpg" },
  { code: "NZ", capital: "Wellington", image: "/images/capitals/1.jpg" },
  { code: "NI", capital: "Managua", image: "/images/capitals/1.jpg" },
  { code: "NE", capital: "Niamey", image: "/images/capitals/1.jpg" },
  { code: "NG", capital: "Abuja", image: "/images/capitals/1.jpg" },
  { code: "KP", capital: "Pyongyang", image: "/images/capitals/1.jpg" },
  { code: "MK", capital: "Skopje", image: "/images/capitals/1.jpg" },
  { code: "NO", capital: "Oslo", image: "/images/capitals/1.jpg" },
  { code: "OM", capital: "Muscat", image: "/images/capitals/1.jpg" },
  { code: "PK", capital: "Islamabad", image: "/images/capitals/1.jpg" },
  { code: "PW", capital: "Ngerulmud", image: "/images/capitals/1.jpg" },
  { code: "PS", capital: "Ramallah", image: "/images/capitals/1.jpg" },
  { code: "PA", capital: "Panama City", image: "/images/capitals/1.jpg" },
  { code: "PG", capital: "Port Moresby", image: "/images/capitals/1.jpg" },
  { code: "PY", capital: "Asunción", image: "/images/capitals/1.jpg" },
  { code: "PE", capital: "Lima", image: "/images/capitals/1.jpg" },
  { code: "PH", capital: "Manila", image: "/images/capitals/1.jpg" },
  { code: "PL", capital: "Warsaw", image: "/images/capitals/1.jpg" },
  { code: "PT", capital: "Lisbon", image: "/images/capitals/1.jpg" },
  { code: "QA", capital: "Doha", image: "/images/capitals/1.jpg" },
  { code: "RO", capital: "Bucharest", image: "/images/capitals/1.jpg" },
  { code: "RU", capital: "Moscow", image: "/images/capitals/1.jpg" },
  { code: "RW", capital: "Kigali", image: "/images/capitals/1.jpg" },
  { code: "KN", capital: "Basseterre", image: "/images/capitals/1.jpg" },
  { code: "LC", capital: "Castries", image: "/images/capitals/1.jpg" },
  { code: "VC", capital: "Kingstown", image: "/images/capitals/1.jpg" },
  { code: "WS", capital: "Apia", image: "/images/capitals/1.jpg" },
  { code: "SM", capital: "San Marino", image: "/images/capitals/1.jpg" },
  { code: "ST", capital: "São Tomé", image: "/images/capitals/1.jpg" },
  { code: "SA", capital: "Riyadh", image: "/images/capitals/1.jpg" },
  { code: "SN", capital: "Dakar", image: "/images/capitals/1.jpg" },
  { code: "RS", capital: "Belgrade", image: "/images/capitals/1.jpg" },
  { code: "SC", capital: "Victoria", image: "/images/capitals/1.jpg" },
  { code: "SL", capital: "Freetown", image: "/images/capitals/1.jpg" },
  { code: "SG", capital: "Singapore", image: "/images/capitals/1.jpg" },
  { code: "SK", capital: "Bratislava", image: "/images/capitals/1.jpg" },
  { code: "SI", capital: "Ljubljana", image: "/images/capitals/1.jpg" },
  { code: "SB", capital: "Honiara", image: "/images/capitals/1.jpg" },
  { code: "SO", capital: "Mogadishu", image: "/images/capitals/1.jpg" },
  { code: "ZA", capital: "Pretoria", image: "/images/capitals/1.jpg" },
  { code: "KR", capital: "Seoul", image: "/images/capitals/1.jpg" },
  { code: "SS", capital: "Juba", image: "/images/capitals/1.jpg" },
  { code: "ES", capital: "Madrid", image: "/images/capitals/1.jpg" },
  {
    code: "LK",
    capital: "Sri Jayawardenepura Kotte",
    image: "/images/capitals/1.jpg",
  },
  { code: "SD", capital: "Khartoum", image: "/images/capitals/1.jpg" },
  { code: "SR", capital: "Paramaribo", image: "/images/capitals/1.jpg" },
  { code: "SE", capital: "Stockholm", image: "/images/capitals/1.jpg" },
  { code: "CH", capital: "Bern", image: "/images/capitals/1.jpg" },
  { code: "SY", capital: "Damascus", image: "/images/capitals/1.jpg" },
  { code: "TW", capital: "Taipei", image: "/images/capitals/1.jpg" },
  { code: "TJ", capital: "Dushanbe", image: "/images/capitals/1.jpg" },
  { code: "TZ", capital: "Dodoma", image: "/images/capitals/1.jpg" },
  { code: "TH", capital: "Bangkok", image: "/images/capitals/1.jpg" },
  { code: "TL", capital: "Dili", image: "/images/capitals/1.jpg" },
  { code: "TG", capital: "Lomé", image: "/images/capitals/1.jpg" },
  { code: "TO", capital: "Nuku'alofa", image: "/images/capitals/1.jpg" },
  { code: "TT", capital: "Port of Spain", image: "/images/capitals/1.jpg" },
  { code: "TN", capital: "Tunis", image: "/images/capitals/1.jpg" },
  { code: "TR", capital: "Ankara", image: "/images/capitals/1.jpg" },
  { code: "TM", capital: "Ashgabat", image: "/images/capitals/1.jpg" },
  { code: "TV", capital: "Funafuti", image: "/images/capitals/1.jpg" },
  { code: "UG", capital: "Kampala", image: "/images/capitals/1.jpg" },
  { code: "UA", capital: "Kyiv", image: "/images/capitals/1.jpg" },
  { code: "AE", capital: "Abu Dhabi", image: "/images/capitals/1.jpg" },
  { code: "GB", capital: "London", image: "/images/capitals/1.jpg" },
  { code: "US", capital: "Washington, D.C.", image: "/images/capitals/1.jpg" },
  { code: "UY", capital: "Montevideo", image: "/images/capitals/1.jpg" },
  { code: "UZ", capital: "Tashkent", image: "/images/capitals/1.jpg" },
  { code: "VU", capital: "Port Vila", image: "/images/capitals/1.jpg" },
  { code: "VA", capital: "Vatican City", image: "/images/capitals/1.jpg" },
  { code: "VE", capital: "Caracas", image: "/images/capitals/1.jpg" },
  { code: "VN", capital: "Hanoi", image: "/images/capitals/1.jpg" },
  { code: "YE", capital: "Sana'a", image: "/images/capitals/1.jpg" },
  { code: "ZM", capital: "Lusaka", image: "/images/capitals/1.jpg" },
  { code: "ZW", capital: "Harare", image: "/images/capitals/1.jpg" },
];

export const getCapitalImage = (countryCode) => {
  const capitalObj = capitals.find((item) => item.code === countryCode);
  return capitalObj ? capitalObj.image : "/logos/logo_dark.jpg";
};

export const getRandomCapital = () => {
  return capitals[Math.floor(Math.random() * capitals.length)];
};
