export const cities = [
  {
    name: "Paris",
    country_id: 75,
    country_code: "FR",
    country_name: "France",
    state_code: "IDF",
    type: "capital",
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    name: "Rome",
    country_id: 86,
    country_code: "IT",
    country_name: "Italy",
    state_code: "RM",
    type: "capital",
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    name: "London",
    country_id: 44,
    country_code: "GB",
    country_name: "England",
    state_code: "LDN",
    type: "capital",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    name: "Berlin",
    country_id: 49,
    country_code: "DE",
    country_name: "Germany",
    state_code: "BE",
    type: "capital",
    latitude: 52.52,
    longitude: 13.405,
  },
  {
    name: "Barcelona",
    country_id: 34,
    country_code: "ES",
    country_name: "Spain",
    state_code: "B",
    type: "city",
    latitude: 41.3851,
    longitude: 2.1734,
  },
  {
    name: "Madrid",
    country_id: 34,
    country_code: "ES",
    country_name: "Spain",
    state_code: "M",
    type: "capital",
    latitude: 40.4168,
    longitude: -3.7038,
  },
  {
    name: "Amsterdam",
    country_id: 31,
    country_code: "NL",
    country_name: "Netherlands",
    state_code: "NH",
    type: "capital",
    latitude: 52.3676,
    longitude: 4.9041,
  },
  {
    name: "Lisbon",
    country_id: 351,
    country_code: "PT",
    country_name: "Portugal",
    state_code: "LIS",
    type: "capital",
    latitude: 38.7223,
    longitude: -9.1393,
  },
  {
    name: "Munich",
    country_id: 49,
    country_code: "DE",
    country_name: "Germany",
    state_code: "BY",
    type: "city",
    latitude: 48.1351,
    longitude: 11.582,
  },
  {
    name: "Prague",
    country_id: 420,
    country_code: "CZ",
    country_name: "Czech Republic",
    state_code: "PR",
    type: "capital",
    latitude: 50.0755,
    longitude: 14.4378,
  },
  {
    name: "Vienna",
    country_id: 43,
    country_code: "AT",
    country_name: "Austria",
    state_code: "9",
    type: "capital",
    latitude: 48.2082,
    longitude: 16.3738,
  },
  {
    name: "Milan",
    country_id: 86,
    country_code: "IT",
    country_name: "Italy",
    state_code: "MI",
    type: "city",
    latitude: 45.4642,
    longitude: 9.19,
  },
  {
    name: "Hamburg",
    country_id: 49,
    country_code: "DE",
    country_name: "Germany",
    state_code: "HH",
    type: "city",
    latitude: 53.5503,
    longitude: 9.9937,
  },
  {
    name: "Benidorm",
    country_id: 34,
    country_code: "ES",
    country_name: "Spain",
    state_code: "A",
    type: "city",
    latitude: 38.5392,
    longitude: -0.1403,
  },
  {
    name: "Venice",
    country_id: 86,
    country_code: "IT",
    country_name: "Italy",
    state_code: "VE",
    type: "city",
    latitude: 45.4408,
    longitude: 12.3155,
  },
  {
    name: "Stockholm",
    country_id: 46,
    country_code: "SE",
    country_name: "Sweden",
    state_code: "AB",
    type: "capital",
    latitude: 59.3293,
    longitude: 18.0686,
  },
  {
    name: "Copenhagen",
    country_id: 45,
    country_code: "DK",
    country_name: "Denmark",
    state_code: "84",
    type: "capital",
    latitude: 55.6761,
    longitude: 12.5683,
  },
  {
    name: "Palma",
    country_id: 34,
    country_code: "ES",
    country_name: "Spain",
    state_code: "PM",
    type: "city",
    latitude: 39.5692,
    longitude: 2.65,
  },
  {
    name: "Frankfurt",
    country_id: 49,
    country_code: "DE",
    country_name: "Germany",
    state_code: "HE",
    type: "city",
    latitude: 50.1109,
    longitude: 8.6821,
  },
  {
    name: "Athens",
    country_id: 30,
    country_code: "GR",
    country_name: "Greece",
    state_code: "I",
    type: "capital",
    latitude: 37.9838,
    longitude: 23.7275,
  },
];

export const getRandomCity = () => {
  return cities[Math.floor(Math.random() * cities.length)];
};
