const z = {
  total_emissions_kg: "531",
  payment_requirements: {
    requires_instant_payment: false,
    price_guarantee_expires_at: "2025-04-19T09:33:26Z",
    payment_required_by: "2025-04-20T09:33:26Z",
  },
  available_services: [],
  supported_passenger_identity_document_types: [
    "passport",
    "known_traveler_number",
    "passenger_redress_number",
  ],
  passenger_identity_documents_required: false,
  tax_currency: "EUR",
  base_currency: "EUR",
  base_amount: "1468.75",
  supported_loyalty_programmes: [
    "AA",
    "CX",
    "MH",
    "BA",
    "AY",
    "UL",
    "QF",
    "IB",
    "JM",
    "AS",
    "QR",
    "UM",
    "RJ",
    "AT",
  ],
  private_fares: [],
  tax_amount: "264.38",
  total_currency: "EUR",
  created_at: "2025-04-17T09:33:26.995370Z",
  live_mode: false,
  total_amount: "1733.13",
  slices: [
    {
      comparison_key: "AwHADQ==",
      ngs_shelf: 1,
      destination_type: "airport",
      origin_type: "airport",
      fare_brand_name: "Basic Economy",
      segments: [
        {
          origin_terminal: "2",
          destination_terminal: "1",
          aircraft: null,
          departing_at: "2025-04-20T14:42:00",
          arriving_at: "2025-04-21T10:58:00",
          operating_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/AA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/AA.svg",
            conditions_of_carriage_url:
              "https://www.aa.com/i18n/customer-service/support/conditions-of-carriage.jsp",
            iata_code: "AA",
            name: "American Airlines",
            id: "arl_00009VME7DAGiJjwomhv32",
          },
          marketing_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/AA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/AA.svg",
            conditions_of_carriage_url:
              "https://www.aa.com/i18n/customer-service/support/conditions-of-carriage.jsp",
            iata_code: "AA",
            name: "American Airlines",
            id: "arl_00009VME7DAGiJjwomhv32",
          },
          stops: [],
          operating_carrier_flight_number: "1274",
          marketing_carrier_flight_number: "1274",
          distance: "8764.812745085965",
          passengers: [
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              fare_basis_code: "Y20LGTN2",
              passenger_id: "pas_0000AtB5e9ZOi60K4M9Ikd",
              cabin_class: "economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              fare_basis_code: "Y20LGTN2",
              passenger_id: "pas_0000AtB5e9ZOi60K4M9Ikg",
              cabin_class: "economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              fare_basis_code: "Y20LGTN2",
              passenger_id: "pas_0000AtB5e9ZOi60K4M9Ikk",
              cabin_class: "economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              fare_basis_code: "Y20LGTN2",
              passenger_id: "pas_0000AtB5e9ZOi60K4M9Iko",
              cabin_class: "economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              fare_basis_code: "Y20LGTN2",
              passenger_id: "pas_0000AtB5e9ZOi60K4M9Ikq",
              cabin_class: "economy",
            },
          ],
          duration: "PT12H16M",
          destination: {
            city_name: "London",
            icao_code: "EGSS",
            iata_country_code: "GB",
            airports: null,
            iata_code: "STN",
            iata_city_code: "LON",
            latitude: 51.885508,
            longitude: 0.236933,
            city: {
              city_name: null,
              icao_code: null,
              iata_country_code: "GB",
              iata_code: "LON",
              iata_city_code: "LON",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "London",
              id: "cit_lon_gb",
            },
            time_zone: "Europe/London",
            type: "airport",
            name: "London Stansted Airport",
            id: "arp_stn_gb",
          },
          origin: {
            city_name: "Los Angeles",
            icao_code: "KLAX",
            iata_country_code: "US",
            airports: null,
            iata_code: "LAX",
            iata_city_code: "LAX",
            latitude: 33.942045,
            longitude: -118.408263,
            city: {
              city_name: null,
              icao_code: null,
              iata_country_code: "US",
              iata_code: "LAX",
              iata_city_code: "LAX",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "Los Angeles",
              id: "cit_lax_us",
            },
            time_zone: "America/Los_Angeles",
            type: "airport",
            name: "Los Angeles International Airport",
            id: "arp_lax_us",
          },
          id: "seg_0000AtB5e9pLkmlSrpc2bb",
        },
      ],
      conditions: {
        priority_check_in: null,
        priority_boarding: null,
        advance_seat_selection: null,
        change_before_departure: {
          penalty_currency: "GBP",
          penalty_amount: "250.00",
          allowed: true,
        },
      },
      duration: "PT12H16M",
      destination: {
        city_name: "London",
        icao_code: "EGSS",
        iata_country_code: "GB",
        airports: null,
        iata_code: "STN",
        iata_city_code: "LON",
        latitude: 51.885508,
        longitude: 0.236933,
        city: {
          city_name: null,
          icao_code: null,
          iata_country_code: "GB",
          iata_code: "LON",
          iata_city_code: "LON",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "London",
          id: "cit_lon_gb",
        },
        time_zone: "Europe/London",
        type: "airport",
        name: "London Stansted Airport",
        id: "arp_stn_gb",
      },
      origin: {
        city_name: "Los Angeles",
        icao_code: "KLAX",
        iata_country_code: "US",
        airports: null,
        iata_code: "LAX",
        iata_city_code: "LAX",
        latitude: 33.942045,
        longitude: -118.408263,
        city: {
          city_name: null,
          icao_code: null,
          iata_country_code: "US",
          iata_code: "LAX",
          iata_city_code: "LAX",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "Los Angeles",
          id: "cit_lax_us",
        },
        time_zone: "America/Los_Angeles",
        type: "airport",
        name: "Los Angeles International Airport",
        id: "arp_lax_us",
      },
      id: "sli_0000AtB5e9pLkmlSrpc2bh",
    },
  ],
  passengers: [
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: null,
      type: "adult",
      id: "pas_0000AtB5e9ZOi60K4M9Ikd",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: null,
      type: "adult",
      id: "pas_0000AtB5e9ZOi60K4M9Ikg",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: 2,
      type: "child",
      id: "pas_0000AtB5e9ZOi60K4M9Ikk",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: 10,
      type: "child",
      id: "pas_0000AtB5e9ZOi60K4M9Iko",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: 17,
      type: "adult",
      id: "pas_0000AtB5e9ZOi60K4M9Ikq",
    },
  ],
  conditions: {
    refund_before_departure: {
      penalty_currency: "GBP",
      penalty_amount: "250.00",
      allowed: true,
    },
    change_before_departure: {
      penalty_currency: "GBP",
      penalty_amount: "250.00",
      allowed: true,
    },
  },
  updated_at: "2025-04-17T09:33:36.632997Z",
  expires_at: "2025-04-17T10:03:26.995371Z",
  partial: false,
  owner: {
    logo_symbol_url:
      "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/AA.svg",
    logo_lockup_url:
      "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/AA.svg",
    conditions_of_carriage_url:
      "https://www.aa.com/i18n/customer-service/support/conditions-of-carriage.jsp",
    iata_code: "AA",
    name: "American Airlines",
    id: "arl_00009VME7DAGiJjwomhv32",
  },
  id: "off_0000AtB5e9pLkmlSrpc2bk",
};
