const z = {
  total_emissions_kg: "212",
  payment_requirements: {
    requires_instant_payment: false,
    price_guarantee_expires_at: "2025-04-19T08:27:28Z",
    payment_required_by: "2025-04-20T08:27:28Z",
  },
  supported_passenger_identity_document_types: [
    "passport",
    "known_traveler_number",
    "passenger_redress_number",
  ],
  passenger_identity_documents_required: false,
  available_services: [],
  tax_currency: "EUR",
  base_currency: "EUR",
  base_amount: "2197.05",
  private_fares: [],
  supported_loyalty_programmes: [
    "AA",
    "CX",
    "MH",
    "BA",
    "AY",
    "UL",
    "QF",
    "IB",
    "JM",
    "AS",
    "QR",
    "UM",
    "RJ",
    "AT",
  ],
  tax_amount: "395.47",
  total_currency: "EUR",
  created_at: "2025-04-17T08:27:28.603554Z",
  live_mode: false,
  total_amount: "2592.52",
  slices: [
    {
      comparison_key: "ttTo",
      ngs_shelf: 3,
      destination_type: "airport",
      origin_type: "airport",
      fare_brand_name: "Comfort",
      segments: [
        {
          origin_terminal: "2",
          destination_terminal: "1",
          aircraft: null,
          departing_at: "2025-04-20T14:42:00",
          arriving_at: "2025-04-21T10:58:00",
          operating_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
            conditions_of_carriage_url:
              "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
            iata_code: "BA",
            name: "British Airways",
            id: "arl_00009VME7DBKeMags5CliQ",
          },
          marketing_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
            conditions_of_carriage_url:
              "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
            iata_code: "BA",
            name: "British Airways",
            id: "arl_00009VME7DBKeMags5CliQ",
          },
          stops: [],
          operating_carrier_flight_number: "0107",
          marketing_carrier_flight_number: "0107",
          distance: "8764.812745085965",
          passengers: [
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Premium Economy",
                name: "premium_economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Premium Economy",
              fare_basis_code: "P20LGTN2",
              passenger_id: "pas_0000AtAzl6kJHCs3vVGa5h",
              cabin_class: "premium_economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Premium Economy",
                name: "premium_economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Premium Economy",
              fare_basis_code: "P20LGTN2",
              passenger_id: "pas_0000AtAzl6kJHCs3vVGa5i",
              cabin_class: "premium_economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Premium Economy",
                name: "premium_economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Premium Economy",
              fare_basis_code: "P20LGTN2",
              passenger_id: "pas_0000AtAzl6kJHCs3vVGa5j",
              cabin_class: "premium_economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Premium Economy",
                name: "premium_economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Premium Economy",
              fare_basis_code: "P20LGTN2",
              passenger_id: "pas_0000AtAzl6kJHCs3vVGa5k",
              cabin_class: "premium_economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Premium Economy",
                name: "premium_economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Premium Economy",
              fare_basis_code: "P20LGTN2",
              passenger_id: "pas_0000AtAzl6kJHCs3vVGa5l",
              cabin_class: "premium_economy",
            },
          ],
          duration: "PT12H16M",
          destination: {
            iata_city_code: "LON",
            city_name: "London",
            icao_code: "EGSS",
            airports: null,
            iata_country_code: "GB",
            iata_code: "STN",
            latitude: 51.885508,
            longitude: 0.236933,
            city: {
              iata_city_code: "LON",
              city_name: null,
              icao_code: null,
              iata_country_code: "GB",
              iata_code: "LON",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "London",
              id: "cit_lon_gb",
            },
            time_zone: "Europe/London",
            type: "airport",
            name: "London Stansted Airport",
            id: "arp_stn_gb",
          },
          origin: {
            iata_city_code: "LAX",
            city_name: "Los Angeles",
            icao_code: "KLAX",
            airports: null,
            iata_country_code: "US",
            iata_code: "LAX",
            latitude: 33.942045,
            longitude: -118.408263,
            city: {
              iata_city_code: "LAX",
              city_name: null,
              icao_code: null,
              iata_country_code: "US",
              iata_code: "LAX",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "Los Angeles",
              id: "cit_lax_us",
            },
            time_zone: "America/Los_Angeles",
            type: "airport",
            name: "Los Angeles International Airport",
            id: "arp_lax_us",
          },
          id: "seg_0000AtAzl722DJ36oTYjiq",
        },
      ],
      conditions: {
        priority_check_in: null,
        priority_boarding: null,
        advance_seat_selection: null,
        change_before_departure: {
          penalty_currency: "GBP",
          penalty_amount: "380.00",
          allowed: true,
        },
      },
      duration: "PT12H16M",
      destination: {
        iata_city_code: "LON",
        city_name: "London",
        icao_code: "EGSS",
        airports: null,
        iata_country_code: "GB",
        iata_code: "STN",
        latitude: 51.885508,
        longitude: 0.236933,
        city: {
          iata_city_code: "LON",
          city_name: null,
          icao_code: null,
          iata_country_code: "GB",
          iata_code: "LON",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "London",
          id: "cit_lon_gb",
        },
        time_zone: "Europe/London",
        type: "airport",
        name: "London Stansted Airport",
        id: "arp_stn_gb",
      },
      origin: {
        iata_city_code: "LAX",
        city_name: "Los Angeles",
        icao_code: "KLAX",
        airports: null,
        iata_country_code: "US",
        iata_code: "LAX",
        latitude: 33.942045,
        longitude: -118.408263,
        city: {
          iata_city_code: "LAX",
          city_name: null,
          icao_code: null,
          iata_country_code: "US",
          iata_code: "LAX",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "Los Angeles",
          id: "cit_lax_us",
        },
        time_zone: "America/Los_Angeles",
        type: "airport",
        name: "Los Angeles International Airport",
        id: "arp_lax_us",
      },
      id: "sli_0000AtAzl722DJ36oTYjiu",
    },
  ],
  passengers: [
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: null,
      type: "adult",
      id: "pas_0000AtAzl6kJHCs3vVGa5h",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: null,
      type: "adult",
      id: "pas_0000AtAzl6kJHCs3vVGa5i",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: 2,
      type: "child",
      id: "pas_0000AtAzl6kJHCs3vVGa5j",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: 10,
      type: "child",
      id: "pas_0000AtAzl6kJHCs3vVGa5k",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: 17,
      type: "adult",
      id: "pas_0000AtAzl6kJHCs3vVGa5l",
    },
  ],
  conditions: {
    refund_before_departure: {
      penalty_currency: "GBP",
      penalty_amount: "380.00",
      allowed: true,
    },
    change_before_departure: {
      penalty_currency: "GBP",
      penalty_amount: "380.00",
      allowed: true,
    },
  },
  updated_at: "2025-04-17T08:27:36.282073Z",
  expires_at: "2025-04-17T08:57:28.603557Z",
  partial: false,
  owner: {
    logo_symbol_url:
      "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
    logo_lockup_url:
      "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
    conditions_of_carriage_url:
      "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
    iata_code: "BA",
    name: "British Airways",
    id: "arl_00009VME7DBKeMags5CliQ",
  },
  id: "off_0000AtAzl722DJ36oTYjiv",
};
