const z = {
  total_emissions_kg: "740",
  payment_requirements: {
    requires_instant_payment: false,
    price_guarantee_expires_at: "2025-04-20T08:22:46Z",
    payment_required_by: "2025-04-21T08:22:46Z",
  },
  available_services: [],
  supported_passenger_identity_document_types: [
    "passport",
    "known_traveler_number",
    "passenger_redress_number",
  ],
  passenger_identity_documents_required: false,
  tax_currency: "EUR",
  base_currency: "EUR",
  base_amount: "1209.72",
  supported_loyalty_programmes: [
    "AA",
    "CX",
    "MH",
    "BA",
    "AY",
    "UL",
    "QF",
    "IB",
    "JM",
    "AS",
    "QR",
    "UM",
    "RJ",
    "AT",
  ],
  private_fares: [],
  tax_amount: "217.76",
  total_currency: "EUR",
  created_at: "2025-04-18T08:22:46.183411Z",
  live_mode: false,
  total_amount: "1427.48",
  slices: [
    {
      comparison_key: "ByDcyQ==",
      ngs_shelf: 1,
      destination_type: "airport",
      origin_type: "airport",
      fare_brand_name: "Basic",
      segments: [
        {
          origin_terminal: "2",
          destination_terminal: "1",
          aircraft: null,
          departing_at: "2025-04-20T14:42:00",
          arriving_at: "2025-04-21T10:58:00",
          operating_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
            conditions_of_carriage_url:
              "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
            iata_code: "BA",
            name: "British Airways",
            id: "arl_00009VME7DBKeMags5CliQ",
          },
          marketing_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
            conditions_of_carriage_url:
              "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
            iata_code: "BA",
            name: "British Airways",
            id: "arl_00009VME7DBKeMags5CliQ",
          },
          stops: [],
          operating_carrier_flight_number: "1516",
          marketing_carrier_flight_number: "1516",
          distance: "8764.812745085965",
          passengers: [
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              passenger_id: "pas_0000AtD3quz3mZqmyAuJgh",
              fare_basis_code: "Y20LGTN2",
              cabin_class: "economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              passenger_id: "pas_0000AtD3quz3mZqmyAuJgi",
              fare_basis_code: "Y20LGTN2",
              cabin_class: "economy",
            },
          ],
          duration: "PT12H16M",
          destination: {
            airports: null,
            city_name: "London",
            icao_code: "EGSS",
            iata_country_code: "GB",
            iata_code: "STN",
            iata_city_code: "LON",
            latitude: 51.885508,
            longitude: 0.236933,
            city: {
              city_name: null,
              icao_code: null,
              iata_country_code: "GB",
              iata_code: "LON",
              iata_city_code: "LON",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "London",
              id: "cit_lon_gb",
            },
            time_zone: "Europe/London",
            type: "airport",
            name: "London Stansted Airport",
            id: "arp_stn_gb",
          },
          origin: {
            airports: null,
            city_name: "Los Angeles",
            icao_code: "KLAX",
            iata_country_code: "US",
            iata_code: "LAX",
            iata_city_code: "LAX",
            latitude: 33.942045,
            longitude: -118.408263,
            city: {
              city_name: null,
              icao_code: null,
              iata_country_code: "US",
              iata_code: "LAX",
              iata_city_code: "LAX",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "Los Angeles",
              id: "cit_lax_us",
            },
            time_zone: "America/Los_Angeles",
            type: "airport",
            name: "Los Angeles International Airport",
            id: "arp_lax_us",
          },
          id: "seg_0000AtD3qvL2SrQo4LBrwf",
        },
      ],
      conditions: {
        priority_check_in: null,
        priority_boarding: null,
        advance_seat_selection: null,
        change_before_departure: {
          penalty_currency: "GBP",
          penalty_amount: "210.00",
          allowed: true,
        },
      },
      duration: "PT12H16M",
      destination: {
        airports: null,
        city_name: "London",
        icao_code: "EGSS",
        iata_country_code: "GB",
        iata_code: "STN",
        iata_city_code: "LON",
        latitude: 51.885508,
        longitude: 0.236933,
        city: {
          city_name: null,
          icao_code: null,
          iata_country_code: "GB",
          iata_code: "LON",
          iata_city_code: "LON",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "London",
          id: "cit_lon_gb",
        },
        time_zone: "Europe/London",
        type: "airport",
        name: "London Stansted Airport",
        id: "arp_stn_gb",
      },
      origin: {
        airports: null,
        city_name: "Los Angeles",
        icao_code: "KLAX",
        iata_country_code: "US",
        iata_code: "LAX",
        iata_city_code: "LAX",
        latitude: 33.942045,
        longitude: -118.408263,
        city: {
          city_name: null,
          icao_code: null,
          iata_country_code: "US",
          iata_code: "LAX",
          iata_city_code: "LAX",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "Los Angeles",
          id: "cit_lax_us",
        },
        time_zone: "America/Los_Angeles",
        type: "airport",
        name: "Los Angeles International Airport",
        id: "arp_lax_us",
      },
      id: "sli_0000AtD3qvLORXiO5RM9Uv",
    },
    {
      comparison_key: "A3aL5A==",
      ngs_shelf: 1,
      destination_type: "airport",
      origin_type: "airport",
      fare_brand_name: "Basic",
      segments: [
        {
          origin_terminal: "2",
          destination_terminal: "1",
          aircraft: null,
          departing_at: "2025-04-30T22:27:00",
          arriving_at: "2025-05-01T02:40:00",
          operating_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
            conditions_of_carriage_url:
              "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
            iata_code: "BA",
            name: "British Airways",
            id: "arl_00009VME7DBKeMags5CliQ",
          },
          marketing_carrier: {
            logo_symbol_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
            logo_lockup_url:
              "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
            conditions_of_carriage_url:
              "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
            iata_code: "BA",
            name: "British Airways",
            id: "arl_00009VME7DBKeMags5CliQ",
          },
          stops: [],
          operating_carrier_flight_number: "1516",
          marketing_carrier_flight_number: "1516",
          distance: "8734.53338837047",
          passengers: [
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              passenger_id: "pas_0000AtD3quz3mZqmyAuJgh",
              fare_basis_code: "Y20LGTN2",
              cabin_class: "economy",
            },
            {
              cabin: {
                amenities: {
                  wifi: {
                    cost: "paid",
                    available: true,
                  },
                  seat: {
                    pitch: "30",
                    legroom: "n/a",
                    type: null,
                  },
                  power: {
                    available: true,
                  },
                },
                marketing_name: "Economy",
                name: "economy",
              },
              baggages: [
                {
                  quantity: 1,
                  type: "checked",
                },
                {
                  quantity: 1,
                  type: "carry_on",
                },
              ],
              cabin_class_marketing_name: "Economy",
              passenger_id: "pas_0000AtD3quz3mZqmyAuJgi",
              fare_basis_code: "Y20LGTN2",
              cabin_class: "economy",
            },
          ],
          duration: "PT12H13M",
          destination: {
            airports: null,
            city_name: "Los Angeles",
            icao_code: "KLAX",
            iata_country_code: "US",
            iata_code: "LAX",
            iata_city_code: "LAX",
            latitude: 33.942045,
            longitude: -118.408263,
            city: {
              city_name: null,
              icao_code: null,
              iata_country_code: "US",
              iata_code: "LAX",
              iata_city_code: "LAX",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "Los Angeles",
              id: "cit_lax_us",
            },
            time_zone: "America/Los_Angeles",
            type: "airport",
            name: "Los Angeles International Airport",
            id: "arp_lax_us",
          },
          origin: {
            airports: null,
            city_name: "London",
            icao_code: "EGGW",
            iata_country_code: "GB",
            iata_code: "LTN",
            iata_city_code: "LON",
            latitude: 51.875482,
            longitude: -0.37004,
            city: {
              city_name: null,
              icao_code: null,
              iata_country_code: "GB",
              iata_code: "LON",
              iata_city_code: "LON",
              latitude: null,
              longitude: null,
              time_zone: null,
              type: "city",
              name: "London",
              id: "cit_lon_gb",
            },
            time_zone: "Europe/London",
            type: "airport",
            name: "London Luton Airport",
            id: "arp_ltn_gb",
          },
          id: "seg_0000AtD3qvLORXiO5RM9Ux",
        },
      ],
      conditions: {
        priority_check_in: null,
        priority_boarding: null,
        advance_seat_selection: null,
        change_before_departure: {
          penalty_currency: "GBP",
          penalty_amount: "210.00",
          allowed: true,
        },
      },
      duration: "PT12H13M",
      destination: {
        airports: null,
        city_name: "Los Angeles",
        icao_code: "KLAX",
        iata_country_code: "US",
        iata_code: "LAX",
        iata_city_code: "LAX",
        latitude: 33.942045,
        longitude: -118.408263,
        city: {
          city_name: null,
          icao_code: null,
          iata_country_code: "US",
          iata_code: "LAX",
          iata_city_code: "LAX",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "Los Angeles",
          id: "cit_lax_us",
        },
        time_zone: "America/Los_Angeles",
        type: "airport",
        name: "Los Angeles International Airport",
        id: "arp_lax_us",
      },
      origin: {
        airports: null,
        city_name: "London",
        icao_code: "EGGW",
        iata_country_code: "GB",
        iata_code: "LTN",
        iata_city_code: "LON",
        latitude: 51.875482,
        longitude: -0.37004,
        city: {
          city_name: null,
          icao_code: null,
          iata_country_code: "GB",
          iata_code: "LON",
          iata_city_code: "LON",
          latitude: null,
          longitude: null,
          time_zone: null,
          type: "city",
          name: "London",
          id: "cit_lon_gb",
        },
        time_zone: "Europe/London",
        type: "airport",
        name: "London Luton Airport",
        id: "arp_ltn_gb",
      },
      id: "sli_0000AtD3qvLORXiO5RM9Uz",
    },
  ],
  passengers: [
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: null,
      type: "adult",
      id: "pas_0000AtD3quz3mZqmyAuJgh",
    },
    {
      loyalty_programme_accounts: [],
      family_name: null,
      given_name: null,
      age: null,
      type: "adult",
      id: "pas_0000AtD3quz3mZqmyAuJgi",
    },
  ],
  conditions: {
    refund_before_departure: {
      penalty_currency: null,
      penalty_amount: null,
      allowed: false,
    },
    change_before_departure: {
      penalty_currency: "GBP",
      penalty_amount: "210.00",
      allowed: true,
    },
  },
  updated_at: "2025-04-18T08:24:15.903303Z",
  expires_at: "2025-04-18T08:52:46.183414Z",
  partial: false,
  owner: {
    logo_symbol_url:
      "https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/BA.svg",
    logo_lockup_url:
      "https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg",
    conditions_of_carriage_url:
      "https://www.britishairways.com/en-gb/information/legal/british-airways/general-conditions-of-carriage",
    iata_code: "BA",
    name: "British Airways",
    id: "arl_00009VME7DBKeMags5CliQ",
  },
  id: "off_0000AtD3qvLORXiO5RM9V1",
};
